### ISSUE TITLE
[Bug]: Saving a new referral gives error message but I can't find/see any errors.

### ISSUE THREAD

**Issue by Info-CBC** [LamplightCRM/feedback#133]
### What doesn't work?

Following on from bug report 106.
I accept the API referral via current version of LL and the switch to new LL to process the referral. Everything works as expected until the very end when I save. Screenshot attached (I've deleted the ID number). However, I can then see the completed

![Image](https://github.com/user-attachments/assets/3f647e54-258d-490b-9eb2-48d238ea5424)

 referral in both versions of LL and there "appears" to be no errors.

### What did you see instead? Did you get a 'Problem saving' message? A 500 error (check Inspector)? Or something else?

Problem saving (please give date and time below)

### Please give more detail on the error

‎09 ‎February ‎2025, ‏‎08:53:39

### Can you reliably make the error happen repeatedly?

- [x] Yes, every time I try
- [ ] Yes, most times I try
- [ ] No it seems random

**Comment by mattparker** [comment]
hi @Info-CBC thanks for this, there have been some updates, would you mind trying this again and see if it's still a problem in your system?

**Comment by Info-CBC** [comment]
Still exactly the same. Tried at 11:34 12/02/2025

**Comment by SamRit89** [comment]
Hi.  I have the same issue.  Could it be where there are mandatory fields not being completed - there is no longer an error message specific to these issues.

**Comment by mattparker** [comment]
Sorry about the to-and-fro here - this has been tricky to pin down. There was another update last night - would you be able to check if the same thing's still happening on your systems?

Thanks

**Comment by Info-CBC** [comment]
Perfect timing! I've just added a new referral and same error message.

**Comment by mattparker** [comment]
Combining similar looking issues:

#123
#260 
#239

**Comment by mattparker** [comment]
Update 20/2/2025 should resolve this but I'd be grateful if people affected could check in their systems again, please?

I think that's @CABaines, @TeamSP00, @Debbie-Harbinson as well as @SamRit89 and @Info-CBC on this thread (sorry trying to copy everyone in from the similar issues raised).

**Comment by TeamSP00** [comment]
Yes this is resolved for me, thank you

**Comment by Info-CBC** [comment]
Yes resolved 😀

**Comment by CABaines** [comment]
Not resolved for me

Carrie Baines
Project Coordinator
01622 828377
www.blackthorn.org.uk<http://www.blackthorn.org.uk/>

My working hours are 9.00am to 4.00pm, Monday to Friday
***@***.***
